/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPollenTileSplatRouteImport } from './routes/api/pollen-tile/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPollenTileSplatRoute = ApiPollenTileSplatRouteImport.update({
  id: '/api/pollen-tile/$',
  path: '/api/pollen-tile/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/pollen-tile/$': typeof ApiPollenTileSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/pollen-tile/$': typeof ApiPollenTileSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/pollen-tile/$': typeof ApiPollenTileSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/pollen-tile/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/pollen-tile/$'
  id: '__root__' | '/' | '/api/pollen-tile/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPollenTileSplatRoute: typeof ApiPollenTileSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pollen-tile/$': {
      id: '/api/pollen-tile/$'
      path: '/api/pollen-tile/$'
      fullPath: '/api/pollen-tile/$'
      preLoaderRoute: typeof ApiPollenTileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPollenTileSplatRoute: ApiPollenTileSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
