/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SafeRouteRouteImport } from './routes/safe-route'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPollenTileSplatRouteImport } from './routes/api/pollen-tile/$'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SafeRouteRoute = SafeRouteRouteImport.update({
  id: '/safe-route',
  path: '/safe-route',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPollenTileSplatRoute = ApiPollenTileSplatRouteImport.update({
  id: '/api/pollen-tile/$',
  path: '/api/pollen-tile/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forecast': typeof ForecastRoute
  '/safe-route': typeof SafeRouteRoute
  '/settings': typeof SettingsRoute
  '/api/pollen-tile/$': typeof ApiPollenTileSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forecast': typeof ForecastRoute
  '/safe-route': typeof SafeRouteRoute
  '/settings': typeof SettingsRoute
  '/api/pollen-tile/$': typeof ApiPollenTileSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forecast': typeof ForecastRoute
  '/safe-route': typeof SafeRouteRoute
  '/settings': typeof SettingsRoute
  '/api/pollen-tile/$': typeof ApiPollenTileSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forecast'
    | '/safe-route'
    | '/settings'
    | '/api/pollen-tile/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/forecast' | '/safe-route' | '/settings' | '/api/pollen-tile/$'
  id:
    | '__root__'
    | '/'
    | '/forecast'
    | '/safe-route'
    | '/settings'
    | '/api/pollen-tile/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForecastRoute: typeof ForecastRoute
  SafeRouteRoute: typeof SafeRouteRoute
  SettingsRoute: typeof SettingsRoute
  ApiPollenTileSplatRoute: typeof ApiPollenTileSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safe-route': {
      id: '/safe-route'
      path: '/safe-route'
      fullPath: '/safe-route'
      preLoaderRoute: typeof SafeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pollen-tile/$': {
      id: '/api/pollen-tile/$'
      path: '/api/pollen-tile/$'
      fullPath: '/api/pollen-tile/$'
      preLoaderRoute: typeof ApiPollenTileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForecastRoute: ForecastRoute,
  SafeRouteRoute: SafeRouteRoute,
  SettingsRoute: SettingsRoute,
  ApiPollenTileSplatRoute: ApiPollenTileSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
